branches:
  only:
  - /.*/
language: ruby
rvm:
- 2.4.1
dist: trusty
sudo: required
cache:
  bundler: true
  directories:
  - node_modules
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  # Firebase API Token
  - secure: "RmLxkrozaETvGJRc8jNL4odd0eqnSa2GNuGllHxgRnAmew05ABJHAC3OERh/lr7TpHYNDoICziOVSVN+FiLCiw7OTqDcP/+e4LhtGxDOZ16SCzz5YUnOx1Qyc1eJhQxwAqgs/3zkqnK1epI9a+qLZhoCya7BjK7RJgCPuPjGlty6O6Cym+UEMWMtpv908vfj0BNsb/eCKxUqtz4rDOA98NCiprGeFBGFqLx4fuYYODobQdsXGpGMSoo3zJWqW6JMqSn8PQwTPeFj9RToLZtrbQADxDfShV6R8oPhPQCeqwmZy6lud9vZbkQVPPrLmJZLq4ovle+m1z2VED8IHXfKH66YdnH5w7JSas4u3fJPbSySAZi5maHauQ8sRwEa8B9PczJjn8EtNd/4OEnWIyv/Js9/eklW6q2mdn4UpM9TLYVazLW5DMg07ZLwYtzOTqt9T0wHGN7oYdIqHA0YUXpGFqS6h/61dE28OXy9sRT/YP4QyjEuo5JTY4kcGVNVDypouMyZL2zwZQ5HNS3LJF6Hq+QTnQbgtoAuTNySnJDZ1p/a101hZPLrqHKmck97DQnKm+8xeFo1IbNrUqdiafD5wTMfEsrD+THDKBLNJWFACKf7Weh0RQAmYk0Yj1e7jqYGFonfuVcE7mUla9elRfmJ478q7jaLnqG+zzgZIGCgjZ4="
  # Stripe Test keys
  - secure: "HBQG7Rhaw6GLIGFnJXHvPAlGrPw7S+MoUtb1qdO2v6ns2W/X57G8s4fKRkqcnmVyhjBNcX3RfsquravLzkY6pQ/tbIy+VAhEdmOxE9J+tWvcvv6RYVo79AMgQZiCjIb4V1kStv9I2lgPObb/NJwvyNtOSFlownFUVpZ/sCcxKfbQEgX4TU60SqQK8w7d1/8jH2ywaw9KIqdsKcr+PkS0NW4ZOFsKixOEFgsqGI+ehHFqyhH7ogoL1D5QLMB8IpS9ax2dwvAFYobSfLxceZcreey11+biIfB0RXgC/bpjNBcAP+ArunMdMK3WD1NKhWTGytbCxaptTO21s1rQxUmry9h/aZFnkViAHIaZN3v79D2GVLwcmj56j6lEGEBaRm8fbcnFR1Woh7qyfP+TU+w+hER2Y6RK27LnIfvlL6qgYN2Uo8Z0pY9ajZ/2StVlxlwN4veLwX9cM+yLv2PuSsDdzlE6kKCiSkSVnLibNMGnFzD+8GIy4c3ciHXLlUlBUkJoKTQke5tJAj2TwKym6oUPY2HOg1AkhAZk/LW2yHKVu5crKeR536t6zCseEPkn3qgUD5H+xM1lrxnnEnF0SE8uBsQPthkJ4ufuMuqWwY7aPoLJADd00mPcmsXpTN1xkAvrIXRboSw4bE/29gQWf/v4avbzTeGB0htJFeqJO1QOTKQ="
  - secure: "QUnGiMWq50ryCO2fVkT8Hxkth8xocAlO+mFcTXru9p94KJNE39c1dmdSe47HnDRWe3L8867iSInQHxTMFTYyzR0+5lY7blghfBIj1/U3BD9ftiiLVdTPM2WysQQIQmxKZ/9UqkyDPDXuSkT7X+iaRg0ijvb3xBxr3p6bqAubUiWm7SVsBN428PvLe+vAhA6yMDUgsFkzoRlABZj/tyZCaiZ3WyZg+g4cl8lsoebveVl3NIQAf+ZW/uLyfzw6dImbshHDpjnXSYB6ASb1Ksd/0l7KhL1V/OyeZ54j8P1pDC7jNSz1fW0yw7OvLgVpLI8N1LV1Eg5OsNfKFYTgyFe91M3khiDo/gsPvsdld0FE986AavKzJu8weGSDoQcl0HnrP1VlyT2foRDapDq8hNwE50QqcJ4qHer4mRZM0estuM7/d/+tJbBKKa92fQmRP4TaieKOXxQi47WSvnYVgJtbrS8ZeJEry25qo9v+jXMCbOiPGx70i38tkHt2+pMk+c1L1Szn6r+U5sdaQxBhH2EFTikgETQW73CtJ5QLHoE6j6/BppVK6J9uOvCdTHwk/rAXLj64PfdOYmLOneNfWCzbJT1pfFjnKEWFg9wapv8WhGGGuo/Ad5mTrMimNeBpalGrqP7wsUny/XlL6U329juD4QzR1Dqtbd4KNrtBmfpkZwE="
  - secure: "c45eWiymcee/1Y2GAuPaD4Xj1fJOFG3PZNCv/z5cWbaDTCZyjY8qYBO2A8tnrdRm4dTXEnKh2Vvg8JdwpyTMoWy3Lcr7aTwE6Dt1Y7VO3UWWK8ZGXOpQdeE77e3CaFuKQ5hfoqqGnWfGMVEeu2mak6C2t3dwCBJTRCeHQGZTJDgB4bRDsMuNe5YCxFZkdaNnNGDQGz8MUBfvowRea/cWEwTK5NeOJg3Scr0t4gzF7CXEpcTszeltXoFeZ/ynYGUPQCwqpxuJMje8ca2tJCc64VKpneG3Sg4wZOX6TkJOIeQTFuEY6FYbkoYu7TfzOEVqVqgkyWPiZ1TWLuzBgeQtR1HD/GGuF2mMFVQCT7oip7/SuRJ7zfniY/2BvDo3zROAGN2Vy+S9iv6U5k5ZpoI23IAke75E1kyB9RzxMT/E4VF+EuBMQJF30ZApryVlJWJoRyOrCs4uL/9Fkyy7hAwUnjr78jDo+pnykeur08AGj0DEuaf9BTtQTvDOWuQaH+F5V4759OXoAy4BIDBBW5zuR1hAslYp8Vpr5EKIAMa56CeIsrVtqGUeFinbORTqgxDc1Tly7dbEzjj8xPm4GRxPoN0WEZ+SH8rAJVywKVdUlUoI+PW2DlJhOpUDnHXfU7GTYr2Cx5rsz22/5R8FZWcw8rV0uDQHUQmS2KUrDAuSZHE="
  notifications:
  pushover:
    on_success: always # default: change
    on_failure: always # default: always
    api_key:
      secure: "nErXOIvEggReYaA6ntqPAYK28aWhEaYqqA0sqz3HHnFuRHYHuQJJnjGGfIeXxhnS5/9PsJ1nY1biC4zVuuQzcFuLRjFfFKNSCtvMderLvIO6AuvpCyOgkwLnvxVH1MHArdHCGvd2lBHOolIoNoyac+yp3+9JcqHL5KS9+1YSfxT+Ei+0NLFbuN2ptUjLlLMXdRqDZbA3421Yc8O9+etfDbUyxoxdt+95/6bT1hlVfZN/O2AKbWyeJHAR9j2gW4d8DVn4J3tWCn2ulltj4On+Nnia5As3WmJKFv4+C5+Jjzyk4jCUyqKwvSjaWu+iYjB1i5cR+ve3LsECi4g1JX5+eqrlOWXedijMGKTA2sfOTGOiomyoRVA5rhH/RtZk8k5jXEg/2UQeo5Ago6Aq7Wz6ssUQA878BduwElPCXyUBeR/JxrrEoFrrKTZCw6n9AbF6exxBBOUvnUBJwUnUhn4R1Ah8Lj1VezWadYXe3K1WVB+B+RJSluhs6FZJv93Kkd3gZgPlEjkU2AzGvFdCH92NuF3A8IoJ6KJG/feD6JGsBSlCM7ads1KSaChVwOFUO/HGYdelsXUiaC5X+Z2MMAQx1dU5MVtn4IgOQZPq/cs3MpdLnJLQ6847Y9kPQKYGDbPKTwq9eOyLAmZDJF+kcIkBAuqbefTQ1br6n/mldrCuCdc="
    users:
      secure: "VH7gJfo++Rh+ivqDGGaqskY0f9aTHz/QHQsRPvHpS8YyAorxgxoUB+Q1uKIgH9WUomldsQCDwfEytEcgTkzcyAVzsBlTYZBPXS2XzK8ZF0nw7STg6oZkAxKuX11ML/iXvgEryRBgfJ5OPUnndhA/tAeL3jNtcPIK5Y7zJwOFZDrwQLi+xxeoWgP8DhkG3E9IlMcM8i+eAldI1JXei9OC6m4iK7R+DszLQa2ges7CnngUWoUbqzy5ErmSBuKK+nHhty88/Y499ciox6LPQH6dDi4VXh5AemJf63MZB3YAap2Npyjyk6AXOf1/DyelKQLGR10o76fs3ajCm7K26+m3hzg0WglM4TjdUdkb+bVujCfj+XBhfLOLsips6YrAZMMXlDEGJHWedeZaAVPHAiDJUqwgL/sqIEIOn8kDlKpNFvA1kKJsz3ab3VrOlc6LJ4Ot1CaGVkL3UV+DZoVw772WXb8MyFKX2XcT+iDE7m+a2OzRF43ZPwkgGFAAINVmXLtkfGEgLRNI6mqAOoJAuSoJ4Ajt5+YYG2Ibn/+aqqAgEex1uVC7ApLi2reTlxJMCsUrZuLYb7TJzPAdMG5xCf6CvYqAdsgLUMG2lFPmRdN6h10O9DyVN3IRIy+tm+WzmmpIFPPGggB12cgyyPBkeRM8GrnApf2itouaobSN8fk3Kzk="
  email:
    on_success: never # default: change
    on_failure: change # default: always

before_install:
- nvm install 9.5
- gem update --system
- gem install bundler

install:
- npm install -g firebase-tools
- npm install -g gulp-cli
- firebase use fir-subscriptions-1ee7d --token "$FIREBASE_API_TOKEN"
# Unset stripe config before setting environment variables
- echo "Configuring Stripe test keys"
#- echo "Configuring Stripe live keys"
- firebase functions:config:unset stripe --token "$FIREBASE_API_TOKEN"
- firebase functions:config:set stripe.publishable_key="$STRIPE_PUBLISHABLE_KEY" --token "$FIREBASE_API_TOKEN"
- firebase functions:config:set stripe.secret_key="$STRIPE_SECRET_KEY" --token "$FIREBASE_API_TOKEN"
- firebase functions:config:set stripe.webhook_secret="$STRIPE_WEBHOOK_SECRET" --token "$FIREBASE_API_TOKEN"
- cd functions && npm install && cd ..
- npm install
- bundle install

script:
- cd functions && npm run build
- travis_retry gulp build --prod

after_success:
- firebase --non-interactive deploy --token "$FIREBASE_API_TOKEN"
#- gulp submit