language: ruby
rvm:
- 2.4.1
dist: trusty
sudo: required
branches:
  only:
  - "add-subscriptions"
cache:
  bundler: true
  directories:
  - node_modules
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  # Firebase API Token
  - secure: "Yplf+kwWBw8mnhyvWEnjIHiSfgjZv2xU1mmMbTLRc/nPp35n5d36Vx6xm+ogQDeEYO7N1Mq7mKwN2c86ls4703TDfnnEsReSgtzGwQ7hGinFTVQnmf+f589T8kosn5NJNPPjQyWZ7tMZeufM6PRF0hyO2xkibYuFWoj3EoFFEPGXGBVGNNiLjx7XtKsHn4Ec+LbtKTx9hw2O1qZeA5TpfMzkZo4mxR0gViUhcS1QsvlSS5OvknHn9vWTX0rTRku2KgvgH5YVho0WOMPdkD62fj0g0ck6VXqPVrcItFcOkE7Pl9hhiU/v8VyW/4hXfIZAgKVWFhnzOtwxpel580iQLs2+OOTLdpw6c3oWaE81qX0350kq8tqW4qWYMh+s9UqJlkHSKRrUZ6Jv+yJ3FGK8t9XyCEBLKKCc0B+nkTQ/6WpABILC8Pn83O4WtCEZ/n8WBmfUGIeAcWUI3wELMwvumxSwqC64hNeByAdB+O4IwcO/V3O4Lv9snjVF5lEq8bGT5D9YS39yD3sW5k5Euid8gf2O160C+XmkoQT8os4VWWaIm1KZU8kxTr3JYgGPys4TESfCe1lbxFtkifeg+T+Ed8V/5JQj8oyR7xkIvSoMGbkeSKXriepy8jlOWTxXyuk9AAACn7XLp5XV0NFfJSmQKUjp2FZmam5Ufi//TArJI4s="
  # Stripe Test keys
  - secure: "HBQG7Rhaw6GLIGFnJXHvPAlGrPw7S+MoUtb1qdO2v6ns2W/X57G8s4fKRkqcnmVyhjBNcX3RfsquravLzkY6pQ/tbIy+VAhEdmOxE9J+tWvcvv6RYVo79AMgQZiCjIb4V1kStv9I2lgPObb/NJwvyNtOSFlownFUVpZ/sCcxKfbQEgX4TU60SqQK8w7d1/8jH2ywaw9KIqdsKcr+PkS0NW4ZOFsKixOEFgsqGI+ehHFqyhH7ogoL1D5QLMB8IpS9ax2dwvAFYobSfLxceZcreey11+biIfB0RXgC/bpjNBcAP+ArunMdMK3WD1NKhWTGytbCxaptTO21s1rQxUmry9h/aZFnkViAHIaZN3v79D2GVLwcmj56j6lEGEBaRm8fbcnFR1Woh7qyfP+TU+w+hER2Y6RK27LnIfvlL6qgYN2Uo8Z0pY9ajZ/2StVlxlwN4veLwX9cM+yLv2PuSsDdzlE6kKCiSkSVnLibNMGnFzD+8GIy4c3ciHXLlUlBUkJoKTQke5tJAj2TwKym6oUPY2HOg1AkhAZk/LW2yHKVu5crKeR536t6zCseEPkn3qgUD5H+xM1lrxnnEnF0SE8uBsQPthkJ4ufuMuqWwY7aPoLJADd00mPcmsXpTN1xkAvrIXRboSw4bE/29gQWf/v4avbzTeGB0htJFeqJO1QOTKQ="
  - secure: "QUnGiMWq50ryCO2fVkT8Hxkth8xocAlO+mFcTXru9p94KJNE39c1dmdSe47HnDRWe3L8867iSInQHxTMFTYyzR0+5lY7blghfBIj1/U3BD9ftiiLVdTPM2WysQQIQmxKZ/9UqkyDPDXuSkT7X+iaRg0ijvb3xBxr3p6bqAubUiWm7SVsBN428PvLe+vAhA6yMDUgsFkzoRlABZj/tyZCaiZ3WyZg+g4cl8lsoebveVl3NIQAf+ZW/uLyfzw6dImbshHDpjnXSYB6ASb1Ksd/0l7KhL1V/OyeZ54j8P1pDC7jNSz1fW0yw7OvLgVpLI8N1LV1Eg5OsNfKFYTgyFe91M3khiDo/gsPvsdld0FE986AavKzJu8weGSDoQcl0HnrP1VlyT2foRDapDq8hNwE50QqcJ4qHer4mRZM0estuM7/d/+tJbBKKa92fQmRP4TaieKOXxQi47WSvnYVgJtbrS8ZeJEry25qo9v+jXMCbOiPGx70i38tkHt2+pMk+c1L1Szn6r+U5sdaQxBhH2EFTikgETQW73CtJ5QLHoE6j6/BppVK6J9uOvCdTHwk/rAXLj64PfdOYmLOneNfWCzbJT1pfFjnKEWFg9wapv8WhGGGuo/Ad5mTrMimNeBpalGrqP7wsUny/XlL6U329juD4QzR1Dqtbd4KNrtBmfpkZwE="
  - secure: "Ful5MQIKn7o+cdg3OTle+PLWF0tM+ar4lvmHJduOtFMMvoDGuiGfDeXPKp3jaeCB/a7ptxcHJM2dGoc389FFTDKem8e69SzZwqNKSFj6bcbnysUDz71uD02UD3lWqGGUTgtcIM36n1B0zCBaeaxg8AiVXkFaXSMdJQ1Pi5H3a/pfB4iJM99d6TSby6xLIRRRnYpiCrU8xDOeEgkQjMiNURKkbzHQSVIcKb5LJlyf6z2fd2bUBmRiQVBQ3QGr6MwWT/pMIQjdY35XsANrFUXye0KC3Z/qhEXZVxJY2+LY1tz2tHF89AFuzTj8ycOOPZt2qOm3/EAFaGpgHrIt2tbePyPnDVnofsJpAripSu4pYOY5z1DN8MruJicXC6QY0iYkbgt/H53KJSwTytBKzTDRjIEjIZc/qUXeVVm61axZfnVOSJG4mpEQvr/9i10zM56U7ZvxliZ0BzSMu8iRXiUMGeaR0R7fyiT28IABEGQ5Bkcti/C1abafowye1UJa4VTAO0hgTqsfirWoAAYDVicBOg4Lhea2oO5QPBSKzbAGv78nQdHD/RZzmzb7XQWM9A1RinNuF2R2Zokkj0DS7NfFIJ9d9niOb2OkNf90fzaOcOKAcHZmNkMyHkiv8JmG93ihUEx/yRfpE/+AISy6T9WmkZcmlBKheh8+R/etRu/0z+I="
  # Stripe Live keys
  # - secure: "PE/16+MsCeExydfYdUvfdeLTxoOrpSoHCV8KFWSaMuZnuk71hFLVJlzUaNJa0mL2jZTCpyx+bmlCWPWkAVgh9EqCOxlyNVDoUodgFzIl0W9yXzWdtyD7rlasrPRcXL++p9yW61HF8nMrfGqkTBzUX5rDQ0bEXCce0Vu8o+MRwGesNAp9RGfG9dOgq5lyOEAKJ4ygylpvSlqZCUM2bOT74DpqutD521puiHoeULfMJIL5qeQapxdIWhKhtbdCPkjNQrZGgqauqztsmlLbLDvZmfEbjo8k2Tb8GAwQLJm6KSb6P9Fol2efP34trgVnMcrHKwvUER7NGux3yqE/8Y5hbP03M/O3fd1znJjWMiTAWG9/yMP3A1usISMesuIMkxXrxj0ulyrodbwiXT3iQ8pW8X2iwwIfRurrIrTlIq40hJxOLilagkper8+SYpj1+/kQFvYkhVrqYs/wC1bwb12cS2+czd41YkCF7nV/jHhr10JgJd4j9BfovhlxyJg035GZULvsLartXYKk1FIqLttQgZxq9Ru8GNRGjg/HUHBgJ3mKq0Q3qLR6ZaxnhwOUyhDcjkH39LAtNA2l7q/2Mqc5sPEts5M4E0ptc9R1rOhl7ATBm8kE9ZD0qjip4ut3i1/bl258qkpq2ysJibRw6GsswlO4ArOXOismhYSetGvGPVc="
  # - secure: "SBYJozcGKSstbU5x6oL5943/EJV66/eV3DQHJUdq6175/LdzE6QuFM1Ti94lo34Pww+nCsykkdYZYurDmy+pDSLHrkiS0N8SjPpT/FXO6z8b/qBVB9UHaCJGVeGYfl38FavvaYBoEUfbE5IIBUDVNBFA0Ar9qExGe25dyGdNKEjIcYsgxuyC9k45UIuG/7CmbAyxltKBp9l0zrC45dbVVehn4EwphkuNareL6iRuZ1fkAUzb3lSXfgai1lTpAAX/X0vvZ7NQ/yOeRPekFOKsi1dbmZD8arcrr3TaRbLhOR9y/peQN4og4XXuwvg9qect5BYL3IBqor7TXgbCBp4qExAYrlX0LEnUAuRkHrvE1JP3qM/ZtDMiG1SQeYs45jyPYB1KUHM5SvUo4NBLRnpx25u3VmvkT8VWxnoSkeDBpH7Wwd2zv6eXp/1vsuqoIynTpRWaO8Ebl9YKp5Ah9Bj9dvR2HRhNuRrp1AU1EDqkDef1O8TGDteYX0IFOzi3uYrrx4rvT7Sxflv6GxuZyzFUHzcpiKsSFEoZSSbBV10NUBpLZw0kGY+Qaj8GeTQNTmeNCKWPHg2t2L/71sSN6qmqCabxjGJRAHJEDIuhUy1nCL3eHCFkNGQsanqYzp7Op/dtvBYif5oba8eyR/I+/7EkNDzOsum6UAjhreRUysUoDkc="
  # - secure: "MKds8WPbCGhX8C2+DC7fvWfBiKM32U1HbVDDSTWV6h6cgIvTa9wn+FBm1Rbz9pj7WPvkyW0UNhtStDw/ZDGIo3d6gqT6E3FdO6Mz75Hs9zrSrfMqCxVA9k4AaJSu2IZNiTuDFiEYmcQow1ULs1Ut9gp7skNs7QDlun9hKqKjgcGns2mywelIUjuRG1bcqUygr2L8xsj4fW4g1kDFNhWyxMComkqugJdGUGzw4HIXH5bUjZim+jO29XrJ+DltP5PL1yzXwIjGaLCG88Wl7DirD3ZIlbE+6D2jzEQaBwTVw/v9xvnr+BcLAp2PudZK3txpmdRnp8FrF1nBBWZGEAuCPa81XpDqYkhd7kooo/C5gIGOVr5jRrdPs6t9tjMYEAsZqAdyTKot0PZ6ORyBHdhJLJeHGG4ynI7tcohf49vdTVCbFaMO+Yg0ONSvOnHwFsdEuS1vPXLd/abSma1kTtiobH10TAQiZN2RNxws1kmpndopDI3w+HKhco4D3tiwgy277iamHXCLFvp+9r/szjnC4H1/oTAhgkJ/OBV6Jc9LLBCatbwinhpW1M1hsu9z2BsfVkFRY2j4+wU4WSDE39R/0ECIVDbeUzykVjLP86WL6PALQfP0F8AIgsTpKnlK91uTMNPxx5ikpm3dfwMIQIIj8maT2B1T0i1uSWDjloOY+So="
notifications:
  slack: it-solver:ndcd4pXcd4mlfIOw59kiIUZn
  email:
    on_success: never # default: change
    on_failure: change # default: always

before_install:
- nvm install 9.5

install:
- npm install -g firebase-tools
- npm install -g gulp-cli
- firebase use itsolver-subscriptions --token "$FIREBASE_API_TOKEN"
# Unset stripe config before setting environment variables
- echo "Configuring Stripe test keys"
#- echo "Configuring Stripe live keys"
- firebase functions:config:unset stripe --token "$FIREBASE_API_TOKEN"
- firebase functions:config:set stripe.publishable_key="$STRIPE_PUBLISHABLE_KEY" --token "$FIREBASE_API_TOKEN"
- firebase functions:config:set stripe.secret_key="$STRIPE_SECRET_KEY" --token "$FIREBASE_API_TOKEN"
- firebase functions:config:set stripe.webhook_secret="$STRIPE_WEBHOOK_SECRET" --token "$FIREBASE_API_TOKEN"
- cd functions && npm install && cd ..
- npm install
- bundle install

script:
- cd functions && npm run build
- travis_retry gulp build --prod

after_success:
- firebase --non-interactive deploy --token "$FIREBASE_API_TOKEN"
- gulp submit
