branches:
  only:
    - /.*/
language: ruby
rvm:
  - 2.5.3
dist: xenial
node_js: 12.13.1
cache:
  bundler: true
  directories:
    - node_modules
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  pushover:
    on_success: always
    on_failure: always
    api_key:
      secure: "$PUSHOVER_APP_KEY"
    users:
      secure: "$PUSHOVER_USER_KEY"
  email:
    recipients:
      - angus@itsolver.net
    on_success: never # default: change
    on_failure: always # default: always
before_install:
- nvm install 12.13.1
- nvm use 12.13.1
- gem update --system
- gem update bundler
- gem install bundler
install:
- npm install -g firebase-tools
- npm install -g gulp-cli
- npm install -g snyk
- firebase use "$FIREBASE_PROJECT" --token "$FIREBASE_TOKEN"
# Unset stripe config before setting environment variables
- firebase functions:config:unset stripe --token "$FIREBASE_TOKEN"
- firebase functions:config:set stripe.publishable_key="$STRIPE_PUBLISHABLE_KEY" --token "$FIREBASE_TOKEN"
- firebase functions:config:set stripe.secret_key="$STRIPE_SECRET_KEY" --token "$FIREBASE_TOKEN"
- firebase functions:config:set stripe.webhook_secret="$STRIPE_WEBHOOK_SECRET" --token "$FIREBASE_TOKEN"
- cd functions && npm install && cd ..
- npm install
- bundle install
- snyk test
script:
- cd functions && npm run build
- travis_retry gulp build --prod
after_success:
- firebase --non-interactive deploy --token "$FIREBASE_TOKEN"
- gulp submit
- snyk monitor
