dist: trusty
sudo: false
language: ruby
cache:
  bundler: true
  yarn: true
  directories:
    - node_modules # NPM packages
    - "$TRAVIS_BUILD_DIR/tmp/.htmlproofer"
rvm:
  - 2.4.1
env:
  CXX=g++-4.8
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - secure: KB+UiNjTyPAvADZqeWdq/KEx62IEUt0JZHfprcyysCPpxrdegdbA6kIXGrcxjzTwmfOHcr6Ksn1S/HqkLr5E6O+OKaLqH4YOA8r9g+GRtHlNdpuK52l6EZmRcdFa6ZgvQyOB+vAZkh68U5BOdill9+V4YasgfFpQYZu+PZam2teoXx+UoiH6MfYv+UCfruC1pkcBdBl7abf9DHFwXDUQAWiA8e4qMG2wC3juHYSJ8tP04k+cotL8XJ+gBd6K9my6mn2ti0HhlvoTcMZodImdAdStp92bKIOey0sYoU0W0frcOVBwa+pO671fPRPKSrWqf0/tAKqv+3N2uegw1VDaJQy/8MqOsLfrGbvprdmDsqGpk3Vjb+qgNTUvMuX3bZjE7nrH1oKu2bs8bZjHYbE/ooDJtSQystNMT8zi9ol2yiNZ7661CrCbGSgBlaAfX8Ib9lRw4zFYt5G3t5QjmBV0Bhdi1z50jLI0ip51SYCDWD44/vx9dx6m7xgVuZ9EURrKt2Sq/ujoD8JEJxjMIN2VYTpcdc8TEjk/Gyl2xppYgXPuH3qxnPQVtKECQHA5oRmxolKzCkLnrU+DC8SstO7jpkWK/dMhLK0nKpf9q+RpOGhtuLruZloAr9m8hgsX8E1hfmD3SWntnNugudmiDlcZdmaoQRUSIRpPSxnYVhuvT3I=
    - secure: OqEVfyee5pM2pGXWSdTU7I2a7bWbdnDaQr6k2ORegEohCkX/+YmhlmMv2vAFdI3Es8HHz+F5aI8ychs+PLgxQ9vuLoSfaL00pty/a5XsJDkoeRwKLVCPdNxtoDryu2LgFJ9DdCeBd7ZCI2twVbXM3LHIu0ZZ4W863h18Aj/xxohWZzz8maH7d631gbSoALkdY17ReYZ/fKKRZqiTbQs6CzYW9H8UyQmq0mqhevcKrg40ZZNk+/xfAyzVW4/PfGAkw2UlxCBkawzOQ+rBzqnpp6CLlYbc1IuEXqdweAV/tI5BAKjRmife4r6BNf8EuuwSnbJavoWVt1ZC4UIcKzQJbvp1J0atCWEMoOGSNkvI2B5u2xSK9FDNQFjY0nCyhuikm/pj47czNMh1C83kuywZ0crMs9Z2MinubRBfmVUcUFktWaOBhYXP2MG1QMvfmXxw9uTuT2k07t4Ctm8/RqcyQ0/NtfSMbWgbluE+42NQKyeqCEFQ5Uqhrb7DTm/sb+gleNKWg526mhLT4l3povkoqHdDthZFpuhsSM7FVazx14GNMvyGSHnzKkGO4+U/6ZdJGrgH25dtEP4c0vaFIc2qO4huHa7NOqqhFX4QYFqgeXZkzCOpQVpSVR3hMBXg4tkF4tengHTkFDvr+JMQWnraMTzghC367Y7rhXjuHMIcvKg=
    - secure: AqigA4E8/05xVUIFWuUMa+F2dJSQzuBWyGGdjzdiwbX9LzDJzwGCTwjPCvSeP3alvj14eMuFoWmau8Hanu02vvRVHh0CDLi+wegOMDVYpcD8DQEH5R/179Vv7WKMp4mayHAKCXRYC1aLEmsGw/U6yrZebrgVmBWqWQFo6zhW66ARzEPq3SRptK9fFzt38ezmP9W64e0RG95AOva8ja5zuRVG7O0HCz+cnRBlESc7OpZKxJQ/1j3YtqeXM5amzQoGtTjEFNJabJLFrj38kAH3jl1Cmj/vdQUlDxSLTiChGWuW6oBm6+Xu9E2g2eFAhJ2tot9sY/og+9XSndXz4V9MDe9EfKtG3Gg5Ogr7oxL/nB319ENBXBU0jBLdLKF+BF0EWR7WD4VrN99rcC8S5cbjsaClxntqBS5BjXeGvIvq0pxhsD2UkuYnKbezmZOXQ+aD8xrc0cGgp9+rGAkKQW4JlPrzdYW3bguouIEGTzuPW0xmXH/WJvg4Vk23ldCOlNJKKKstzlB1BXxVSADGrmfEglr6xkHjjCILpieOJVGOeDTjEetzGw4uhMJtbmGH1D3pMyzJJwx3dMETkuUZ62qt/z+cEcuuJ+youYv8guceIXeKKLjv2HGoZzjSbPHhKeEstlU17tR8McEYeTOgFPoBr0XB4CMBPzfbH+ZlgV42euY=
notifications:
  email:
    on_success: never
    on_failure: change
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
install:
  - nvm install v7.10.0
  - npm install gulp-cli -g
  - npm install gulp@next --save-dev
  - npm install yarn -g
  - yarn
  - bundle install
script:
  - gulp build --prod
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "$FIREBASE_API_TOKEN"
  project: "$FIREBASE_PROJECT_ID"
after_deploy:
  - src/_script/proof-live