language: ruby
rvm:
- 2.4.1
dist: trusty
sudo: required
branches:
  only:
  - master
cache:
  bundler: true
  yarn: true
  directories:
  - node_modules
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: "Yplf+kwWBw8mnhyvWEnjIHiSfgjZv2xU1mmMbTLRc/nPp35n5d36Vx6xm+ogQDeEYO7N1Mq7mKwN2c86ls4703TDfnnEsReSgtzGwQ7hGinFTVQnmf+f589T8kosn5NJNPPjQyWZ7tMZeufM6PRF0hyO2xkibYuFWoj3EoFFEPGXGBVGNNiLjx7XtKsHn4Ec+LbtKTx9hw2O1qZeA5TpfMzkZo4mxR0gViUhcS1QsvlSS5OvknHn9vWTX0rTRku2KgvgH5YVho0WOMPdkD62fj0g0ck6VXqPVrcItFcOkE7Pl9hhiU/v8VyW/4hXfIZAgKVWFhnzOtwxpel580iQLs2+OOTLdpw6c3oWaE81qX0350kq8tqW4qWYMh+s9UqJlkHSKRrUZ6Jv+yJ3FGK8t9XyCEBLKKCc0B+nkTQ/6WpABILC8Pn83O4WtCEZ/n8WBmfUGIeAcWUI3wELMwvumxSwqC64hNeByAdB+O4IwcO/V3O4Lv9snjVF5lEq8bGT5D9YS39yD3sW5k5Euid8gf2O160C+XmkoQT8os4VWWaIm1KZU8kxTr3JYgGPys4TESfCe1lbxFtkifeg+T+Ed8V/5JQj8oyR7xkIvSoMGbkeSKXriepy8jlOWTxXyuk9AAACn7XLp5XV0NFfJSmQKUjp2FZmam5Ufi//TArJI4s="
  # Stripe Test keys
  - secure: "XvzAlFV1WN+jTrLYKGiUe3gVX7tS2rWNodiDdLppT3KKzQTHoGzHc3aP7AXdgSDF/ZTetACzxW6UJZ+Amgdn7QcMOF+RWugytk5frMCy49df9IaBqsZm5Z6vkk9CtgLg9lbO6IMJVDFuRuKSr2TLPeNYovS2j9W1Vrpg6kExsTvynOTBuLLzXPNyC8Rv/fyxCw8UJ/WUZSuPL1iYE5uVRWa1pdHW+45N05dr7mWbZplK87fGwu7+2QUxzaD3dcfRGAwDt3MQe/fK4t6smOgbxsfgF9H6mlD5tOj0vjtVLnqA72o7hr7/6PvGKi/C1bf4wTJbfMMbaJMOt/ehPjH6mOGgBgesNTFhODvf4xyGvXdk3xeh8DkkpEADdRyXifsu8i+xJW2VZ0BGAck2D9hxaPacde2v5nUlt/fQ0icBm+B2DiPtQj1y+CgF12Mr5ezNxN/Ik08YYQ8Azbyke2XPALIBlCronantYDI2cTiovMtTNhW/cci13p0EHpIT1FNXFSvXC3EzlYUa2AXlVLbecUCYjOy3MlutdN/ABqIVyvBnN2+wAo1Y4jVPxjljDzzTl6kOAbmxJuiF9+KwIisUQgVaulxUc0SthJ+BISDoibvGwX8pco+65nEqhIbvRSUCPwk1gW/sn3QambCTEabO4TIleryvqkCtyKMp9vTjlGg="
  - secure: "sH9b0yTwHDcBKzwyFLUo9kIV2+zts8SUnlv08Z43nzp7RRiDZXUIxJ13uIsag56y+K66QpkjUWJB80QlUj50N6q0Zptue9OMWzFvphBfW0BGRY/e/rePKmNqFekoilCGFNKtc//hVUrykgb539rbMPnGLKt6yGb9rHlxHsJa2+XxrMKpPbiZvfRsD3FVfMeWeLDLnPEw17Kz/kqoVpL0XHdf/Tm1V9MQME69YufwidsmYY1IEOPO1chQj9D3GzS6hl/YqjvN5C2TuANAQgN97fBcoeY5mlR0I0V4r2MillsW1XoYsLCqEjtCTHPTMh5lvyhce8hYghKBegtWSsMy/SImQ7sMk1D9RUtsvc5G18/ZYMXFrZcUL7fPpfGK/u5blMP0j294q7JLGOcsSmAeJq00LnTy5fRW5F6nGFIq3YqU3ymUyDp87lY4gVdzXbh4X4apl8Zcf9KpTUb0+DttTtg/XlNaU0ONSqCS1iY3XTcKgYcF+fqW2GqBB8X1RQEPaGrHemLZqqrUC3v7XkmDXTx958ADw5xgEmClJhkq49z3pMynBZxF6ArRDrGITENzp2RqkG0BIpsNX8sax0dGJV7eqy+sB7J7U7mrOJFV8+chAC56cvuomACkMN8RlNhiFFkRJcaBH55O/NLKarZ9GVnxiCsA4uB1FNEkCUUND4E="
  - secure: "IROERna7eyv2eDRlFcQfEq00H4eVrx42whdvO/reTF2JyWBG19mCGZpdUWIP5WJx47AX8lHNh00RC9pqsfTM5d8AJ043GGRog1WEv8iIoSOvZHgwudfsIwMa172NkH3hAt/A2u8GzgbPLhYy61z4+SnsMQOMsYZ2lMY4yB4IVWM8nZuCP3PVZ90x8kRcPR4lJaiXdRd5Mknfme65mQFOjq8M9DaP/nnp0iZsEOJC+LZ8QviDRuDgJ52QST6FAMl+5zSRS5mms17YLa+8IFpQmmqlWSIViWy50Jz6VxTp7P5PAsklaJr/eB7IaHQHiOAfifM5OFtuSE8AFIhxn+7ayI2xXqgD6QbtE22fz/dGNbLZ/mvjwhHL58aeuhu0+rfn5leBUBBQFSNJqictZXtQ2mJBZ3HCNM7Eb9Ve2YDg8fvROKqaOioTMmpkpN700BLLC6fkyE73+gvuvBL1nksrcpR6Asp8LM3yqksdHq4mJE52up2IR5JKScO/NpuAWfaq6+b5GbjJcUriCCOHTYPb8hCgJFEMUIK0/ALrQA7p2LfHs0YhEDNTAuUTv+rG7Llblnw6LzZ2x9dPL8K6j6QCqiBrWvYAvzQKFHAPJSgg4mP2qY9q7AwkGWI9SDiEFCeTVIeVU5Qi/LMuoXRFSmBIQGNlsdlQm00IQzhNKi++z7o="
  # Stripe Live keys
  # - secure: "FpeZZY1tqPlXZ+Vwd4EcL/u584XQE/HxWTsmrL73qeAOnAfUvYF6N30Gd+X3ef6IG895EoSFk36Nx6gzOt/qgQWhkc44CgDv78zdWQgUpUUbZOPEWRApKq3vLxVgLI8tMSUhwLyhjdtfaE9X20d0za0k8o/5rA/5vkKHJ/MUO89vGT4tCqOgh9aWzSDIY+nvvO5lHGdcKQKUhxhNMrBP5kSIZ/buH8FPLhFArGsnmJf0A5a/ZntU7DdEHAWrobfeZJ9xJ1jambuKdXCFnP5WuM+vCTGqRUBmU4GpCyopmrJrNcJsgnH8kxdg3KAPEc3R6f9js3EHsZeAcXi4yNxjNvHmjQ0rfQf/julBJOGPgrShE5RGgFA7nIWzpJvyFlglPw+kmA7K9RP08MUyRPyDYeSkXwCU6BPX6RbCnBE8Ty/WFaiWV+k2YK+aDdzE+MjXUotcgoHUii5mvL3T5sJSqU7aXA8uzrA2TfnEEhjOTsbZlBjiloNlLC5mKZsr9I5gBY/Rz41oPumSLD8elODcK5kj3jBrl0VBM4jyPCH8lwDMilDDhvevphz+FmQvMcxA8TdRGvqyDUcBniDHbgBF/4kR6nZ/wzuoa05noGSy4kf09h3Q767oCE9aH/IOTnG/bdPVczhSVt9Jr8BITB5nLBED5AaDwzqx4LW8GVdGrYc="
  # - secure: "EO4+tACvUiTaNAo44L3XOYRI10St+XmFkEGBdl/1ddDkzQcNPPBItphrcGwZkDyUTy5cyXpJ9Ww1OLcTRxKVqA8n3+i2LDYRlggh/kdccsfh7RikYJeMH9Nfj5cHcJHnRnTWs76Ik+LUrs3X1LoAsKeP4HeyWuCDeyU4HrWwC5sYbSOKmjRSDE0XoirYGnziE1P05NDk/6MZm9hSa6urTtHybP4flaQj5QtoMyxM40Cb/9gr2X53vB6t25Z2ZaSIcsD7PZ+ntIH3Pyuku5QEExbkPmXEnFYtLZtU1wTbL7I7OQu5EFdJC1J81KwSJgyEFwrzIpSnszSfxmX8A9OAZr42Bx7qIQNJFoDoPAULpD+JHKEtDia3VfwMyU3brnr1Dws3wwJI6gO0lC5q+ISanmfR95CrfYjTh9Lcpy5GjzzLAVxEGSJGTZZOInrRB0CQF5UimtGjFiLkT2NOdUnsL2CHp3V4SB5Pdk828etQ3HGdSky+a+0WMQkME+VnF7MakoCsAyZv6jeWAJT8QftBZwE6DQBsBM90xivJ4Cp4kiYPzlnG9OClNE9IRov6uC324sV9da5OsxAbPj7QbGcBWlLf0kmuGzc9hyAmf91x/XMDlxIEl48zn5KLxmnXuE7tLAFvcuIXyjD76C1mkM30h84Yq/cMuraylMJWu9adsCY="
  # - secure: "C1+fz7RJosmljDWtOUjXr7LBgsyamuu7ylRWiv6IJ+WBgO9KYq2+wjK2Nq/PRYWbHdLkL9CWo2TVBopdYl8BGG++fWcEiUYlB9yECpyEM9rp8Lsl5wojDrQ49kUydLUUkHskLBn89rowGa4lbTgKGzhRcM0/htt+bLD+TSoTDaX0GZy6/IMh/yi/0jmE2mzBSJMSY+DsK9xUtF/dXU6vBWWLdwAFXRsFjTaaRziDVwfXYbILpMwDry/3LkCLyVOzFSV3AeUWh99nRFpo/Q7B54/SuzPCwgTbq33og2IkRP7TlHvBRiqPzbm47bJokwQYkcs2RixsQyoV63mVMMVV22y4a1vlS9Y/PjF8Ax2GeVr3pag0qRbQVlRKHlaNWMlh51bljALoz5I0EQYxtOTv/W3h2A4N/VgVOjD1MaPaf9GSl+diB7FTcl4JZe5bwBnEL5BQI+lFAlygrfniqRcGMnt7E7AUzBgM2Qx4wC7usJBFk7LLelOV08bEQsChNKkbLnSutagkiCw4qhwr3/GT/UbBekB3EB9eDjTqJ15EZTWXXUVrvBGe2OUhYdCYM/D/aW8GYOVCn/7NeHqNQC/oepqFU/858Vm5vrpoB4YiOQT6Sxlexdjbfz4UdjpvCteyuHqkhnEVnOo1p4NGKv0m2zbHIu9+z3Waat9plKZD3RA="
notifications:
  email:
    on_success: never
    on_failure: change
install:
- nvm install 9.5
- npm install -g gulp-cli
- npm install -g firebase-tools
- firebase use itsolver-499d1 --token "$FIREBASE_API_TOKEN"
- firebase functions:config:set stripe.publishable_key="$STRIPE_PUBLISHABLE_KEY" --token "$FIREBASE_API_TOKEN"
- firebase functions:config:set stripe.secret_key="$STRIPE_SECRET_KEY" --token "$FIREBASE_API_TOKEN"
- firebase functions:config:set stripe.webhook_secret="$STRIPE_WEBHOOK_SECRET" --token "$FIREBASE_API_TOKEN"
- cd functions && npm install && cd ..
- npm install
- bundle install

script: travis_retry gulp build --prod
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "$FIREBASE_API_TOKEN"
  project: itsolver-499d1
after_deploy:
- gulp submit
