language: ruby
rvm:
- 2.4
dist: trusty
sudo: required
branches:
  only:
  - master
cache:
  bundler: true
  yarn: true
  directories:
  - node_modules
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: Yplf+kwWBw8mnhyvWEnjIHiSfgjZv2xU1mmMbTLRc/nPp35n5d36Vx6xm+ogQDeEYO7N1Mq7mKwN2c86ls4703TDfnnEsReSgtzGwQ7hGinFTVQnmf+f589T8kosn5NJNPPjQyWZ7tMZeufM6PRF0hyO2xkibYuFWoj3EoFFEPGXGBVGNNiLjx7XtKsHn4Ec+LbtKTx9hw2O1qZeA5TpfMzkZo4mxR0gViUhcS1QsvlSS5OvknHn9vWTX0rTRku2KgvgH5YVho0WOMPdkD62fj0g0ck6VXqPVrcItFcOkE7Pl9hhiU/v8VyW/4hXfIZAgKVWFhnzOtwxpel580iQLs2+OOTLdpw6c3oWaE81qX0350kq8tqW4qWYMh+s9UqJlkHSKRrUZ6Jv+yJ3FGK8t9XyCEBLKKCc0B+nkTQ/6WpABILC8Pn83O4WtCEZ/n8WBmfUGIeAcWUI3wELMwvumxSwqC64hNeByAdB+O4IwcO/V3O4Lv9snjVF5lEq8bGT5D9YS39yD3sW5k5Euid8gf2O160C+XmkoQT8os4VWWaIm1KZU8kxTr3JYgGPys4TESfCe1lbxFtkifeg+T+Ed8V/5JQj8oyR7xkIvSoMGbkeSKXriepy8jlOWTxXyuk9AAACn7XLp5XV0NFfJSmQKUjp2FZmam5Ufi//TArJI4s=
  - secure: s01OHQ38v/KAKkgMlam2qYX80ND7mHmuN+V1QslQrKaK7sxtzuHYEEj+XPO++xywQIL2ZwzQc6rjvxgcznfSBKj/pnUqjj2KwsL+iPreW9tLX5qtWlQWYtCg1AGW30Vib5dMp2DF68hwYKKmVQqX+bn0jX7Z25FGvgMdXtystwLqmuUyFMiMj+2VxYrawo9E8ic/tp7Z+RmBz3BVodqF7u0D53/RAmP7c4GnIuE7tKSXK1FcqW40DdG77/uzmGKITt17mFCWmYExVw6KFHlPJF9VNkklLeeCnDOmYONlLDK7gPbaz4nP0gjyvK/VHoue9OHI5qgkr46tPNDN2wVeF00L//tGSRtQz/l9oj5C4KzSurUm22X+iC0Iqo1Wj6BV8TwEPoPPp0RcH8yuJWvfAB1LabrS8v6TxxYMWQZcOYRFYrDhO0YCCytaMFVG7MzyT+ONts5cmnwlCTxhQCxNgfNE7hK2aUZVPMlEQTPYBBCYyGjZy9oGk5Ywm/rK1Ae9RcnXiAYl8l5z/HGaa79d26Gp4R3PbGYxZO4nnm5j8ycTIyff3muHdpQVUfqGYrUdNLVubPTI/j92qKMRJ9RGF6xATFRrdbR8DCDiQTfDq1SVJpJHPDjDslDUKzyoqq7YqhRdC2gAlENRkMpgfkIuGntu9Ipmn/rqtiYkEY39iAw=
  # Stripe Test keys:
  - secure: bUdWVLdD/KzV58MufcECNGJXwEWsQby0Sj0chJR7cOKFfkHWF/rm0pnzOsQS9wZTACXodvR6AEkKj5rcV8axj6EYGBIc+bUUAvDZKp8qHSnXj7U+ZqasNQkoTLO1ztKQa+fbM6dnFfEfHSCs9lHEPgFk7RfMW6U2/J/J5FfBHN+G/DhU3EDB/fQj04lBSfC2FSHfL36ucrsfi8+EAEzzRGOG/ubMpNkC1KLrl/eSd9gW+3FqQLMszU7eFNQprPqYtpLSNlsJqMM87Tst+2yC0MHn28YTVqxtGz8r9P5Rof/k/dM0qE6AWG1nhilPPRXEkEZ70ZXRE7xigEKkaSWCcqK/VJ6v90tmuA8twAP+LiodMGUXFU1vZZ20NUnD0ZLsoAZ2GZJY0vUw+kiam6ENKl+I3/9zbVbJD+ZBkIMx/zavAETSDDZaDcYjwTwRhX0ZuEGSA+SfKIFjAL9oiCH97131bQFmfIaLU5mkctjwkn7aKcKVUM6mJeq1DnW5aIsSxkCGfMxRgT512Q+QuI8st5wFRUdROBVoKnfoRB3c+61k7z9bn58wlbRdpXWZ99rLlcHyynwX3A7GVFTGQX0W5w5Okd1lLVWaUVtYwmTxmWcHHTgJHmdQ6tXl2y5Tj6QqJC2XzWwKN6LE+O9Qvr5Jzx0QiSZEM1/QaNpnr5Rw9pU=
  - secure: sH9b0yTwHDcBKzwyFLUo9kIV2+zts8SUnlv08Z43nzp7RRiDZXUIxJ13uIsag56y+K66QpkjUWJB80QlUj50N6q0Zptue9OMWzFvphBfW0BGRY/e/rePKmNqFekoilCGFNKtc//hVUrykgb539rbMPnGLKt6yGb9rHlxHsJa2+XxrMKpPbiZvfRsD3FVfMeWeLDLnPEw17Kz/kqoVpL0XHdf/Tm1V9MQME69YufwidsmYY1IEOPO1chQj9D3GzS6hl/YqjvN5C2TuANAQgN97fBcoeY5mlR0I0V4r2MillsW1XoYsLCqEjtCTHPTMh5lvyhce8hYghKBegtWSsMy/SImQ7sMk1D9RUtsvc5G18/ZYMXFrZcUL7fPpfGK/u5blMP0j294q7JLGOcsSmAeJq00LnTy5fRW5F6nGFIq3YqU3ymUyDp87lY4gVdzXbh4X4apl8Zcf9KpTUb0+DttTtg/XlNaU0ONSqCS1iY3XTcKgYcF+fqW2GqBB8X1RQEPaGrHemLZqqrUC3v7XkmDXTx958ADw5xgEmClJhkq49z3pMynBZxF6ArRDrGITENzp2RqkG0BIpsNX8sax0dGJV7eqy+sB7J7U7mrOJFV8+chAC56cvuomACkMN8RlNhiFFkRJcaBH55O/NLKarZ9GVnxiCsA4uB1FNEkCUUND4E=
  - secure: IROERna7eyv2eDRlFcQfEq00H4eVrx42whdvO/reTF2JyWBG19mCGZpdUWIP5WJx47AX8lHNh00RC9pqsfTM5d8AJ043GGRog1WEv8iIoSOvZHgwudfsIwMa172NkH3hAt/A2u8GzgbPLhYy61z4+SnsMQOMsYZ2lMY4yB4IVWM8nZuCP3PVZ90x8kRcPR4lJaiXdRd5Mknfme65mQFOjq8M9DaP/nnp0iZsEOJC+LZ8QviDRuDgJ52QST6FAMl+5zSRS5mms17YLa+8IFpQmmqlWSIViWy50Jz6VxTp7P5PAsklaJr/eB7IaHQHiOAfifM5OFtuSE8AFIhxn+7ayI2xXqgD6QbtE22fz/dGNbLZ/mvjwhHL58aeuhu0+rfn5leBUBBQFSNJqictZXtQ2mJBZ3HCNM7Eb9Ve2YDg8fvROKqaOioTMmpkpN700BLLC6fkyE73+gvuvBL1nksrcpR6Asp8LM3yqksdHq4mJE52up2IR5JKScO/NpuAWfaq6+b5GbjJcUriCCOHTYPb8hCgJFEMUIK0/ALrQA7p2LfHs0YhEDNTAuUTv+rG7Llblnw6LzZ2x9dPL8K6j6QCqiBrWvYAvzQKFHAPJSgg4mP2qY9q7AwkGWI9SDiEFCeTVIeVU5Qi/LMuoXRFSmBIQGNlsdlQm00IQzhNKi++z7o=
  # Stripe Live keys:
notifications:
  email:
    on_success: never
    on_failure: change
install:
- nvm install 9.5
- npm install -g gulp-cli
- npm install -g firebase-tools
- npm install
- bundle install
- firebase use itsolver-499d1 --token "$FIREBASE_API_TOKEN"
- firebase functions:config:set stripe.token="$STRIPETOKEN" --token "$FIREBASE_API_TOKEN"
script: travis_retry gulp build --prod
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "$FIREBASE_API_TOKEN"
  project: itsolver-499d1
after_deploy:
- gulp submit
