sudo: false
language: ruby
cache: bundler
rvm:
  - 2.4.1
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
cache:
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer # speed up external link checking
notifications:
  email:
    on_success: never
    on_failure : change
addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors
install:
  - nvm install v7.10.0
  - bundle install
script: jekyll build && htmlproofer ./_site
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "$FIREBASE_API_TOKEN" 