branches:
  only:
  - /.*/
language: ruby
rvm:
- 2.4.1
dist: trusty
sudo: required
cache:
  bundler: true
  directories:
  - node_modules
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  # Firebase API Token
  secure: "s413fjBFh05KToiQ7fzM2BmrqEpvQ06JD2JATwRkPH1gNb5yqbYwjtymzUT5N6btNxJvBOhPI78H1CQ2m4gGWVa+yMDF9AJ5WyF9fy0n78ojxucDEMVV/JIPtWmu5JriN+3IVvW3GKcWC3jX9woPUtOIIAksiYHmDeM2QTB7FUm0LRNQKaf23MvVJ3IFpKlGYkXlYnplz5A2oxzFlBQSdeS5CsRge3MEeUUANVhvhL0I+7WZ2ULmzA043x3UwSzZXJ3qSwZoe659uYDExnOzEnK0DnCIEDpMVyRy1lMEMDGQA8j0xRL3jUBiutPFLK8ACHBsc9hvoq3dH3lrNNltcP3TnkqR88fNsJfjWwUB3O1V6LnMYC/6QU34uVVaGGdLUGgPfS7w8n9Gdptb7/v87BdYj7zbV32Vr2TB5YGqsDB+WmLsi0KpCd5YqGS12kdC5iPnGG7v30/obfw3qDY+RHZvjtDRG7F+6fgTa3cPwKo4Su7Ro3USEEMIZvEUTc2zwYH4y/fm1sIYjc2JJNL5b9VgP17OKBiB2I+5czogKwqq1DR3AdSkBdu95MHKdvKMbqFl73o82WZ16jrn2A42V7sPRsnK17rvOsHMlESdkm1FegBTHJJguXr27NRIqitVIOIZjZlZpBQ3etQv6v3s0hej2xFEor4rxDYWp0K8+oI="
  # Stripe Test keys
  - secure: "XvzAlFV1WN+jTrLYKGiUe3gVX7tS2rWNodiDdLppT3KKzQTHoGzHc3aP7AXdgSDF/ZTetACzxW6UJZ+Amgdn7QcMOF+RWugytk5frMCy49df9IaBqsZm5Z6vkk9CtgLg9lbO6IMJVDFuRuKSr2TLPeNYovS2j9W1Vrpg6kExsTvynOTBuLLzXPNyC8Rv/fyxCw8UJ/WUZSuPL1iYE5uVRWa1pdHW+45N05dr7mWbZplK87fGwu7+2QUxzaD3dcfRGAwDt3MQe/fK4t6smOgbxsfgF9H6mlD5tOj0vjtVLnqA72o7hr7/6PvGKi/C1bf4wTJbfMMbaJMOt/ehPjH6mOGgBgesNTFhODvf4xyGvXdk3xeh8DkkpEADdRyXifsu8i+xJW2VZ0BGAck2D9hxaPacde2v5nUlt/fQ0icBm+B2DiPtQj1y+CgF12Mr5ezNxN/Ik08YYQ8Azbyke2XPALIBlCronantYDI2cTiovMtTNhW/cci13p0EHpIT1FNXFSvXC3EzlYUa2AXlVLbecUCYjOy3MlutdN/ABqIVyvBnN2+wAo1Y4jVPxjljDzzTl6kOAbmxJuiF9+KwIisUQgVaulxUc0SthJ+BISDoibvGwX8pco+65nEqhIbvRSUCPwk1gW/sn3QambCTEabO4TIleryvqkCtyKMp9vTjlGg="
  - secure: "sH9b0yTwHDcBKzwyFLUo9kIV2+zts8SUnlv08Z43nzp7RRiDZXUIxJ13uIsag56y+K66QpkjUWJB80QlUj50N6q0Zptue9OMWzFvphBfW0BGRY/e/rePKmNqFekoilCGFNKtc//hVUrykgb539rbMPnGLKt6yGb9rHlxHsJa2+XxrMKpPbiZvfRsD3FVfMeWeLDLnPEw17Kz/kqoVpL0XHdf/Tm1V9MQME69YufwidsmYY1IEOPO1chQj9D3GzS6hl/YqjvN5C2TuANAQgN97fBcoeY5mlR0I0V4r2MillsW1XoYsLCqEjtCTHPTMh5lvyhce8hYghKBegtWSsMy/SImQ7sMk1D9RUtsvc5G18/ZYMXFrZcUL7fPpfGK/u5blMP0j294q7JLGOcsSmAeJq00LnTy5fRW5F6nGFIq3YqU3ymUyDp87lY4gVdzXbh4X4apl8Zcf9KpTUb0+DttTtg/XlNaU0ONSqCS1iY3XTcKgYcF+fqW2GqBB8X1RQEPaGrHemLZqqrUC3v7XkmDXTx958ADw5xgEmClJhkq49z3pMynBZxF6ArRDrGITENzp2RqkG0BIpsNX8sax0dGJV7eqy+sB7J7U7mrOJFV8+chAC56cvuomACkMN8RlNhiFFkRJcaBH55O/NLKarZ9GVnxiCsA4uB1FNEkCUUND4E="
  - secure: "IROERna7eyv2eDRlFcQfEq00H4eVrx42whdvO/reTF2JyWBG19mCGZpdUWIP5WJx47AX8lHNh00RC9pqsfTM5d8AJ043GGRog1WEv8iIoSOvZHgwudfsIwMa172NkH3hAt/A2u8GzgbPLhYy61z4+SnsMQOMsYZ2lMY4yB4IVWM8nZuCP3PVZ90x8kRcPR4lJaiXdRd5Mknfme65mQFOjq8M9DaP/nnp0iZsEOJC+LZ8QviDRuDgJ52QST6FAMl+5zSRS5mms17YLa+8IFpQmmqlWSIViWy50Jz6VxTp7P5PAsklaJr/eB7IaHQHiOAfifM5OFtuSE8AFIhxn+7ayI2xXqgD6QbtE22fz/dGNbLZ/mvjwhHL58aeuhu0+rfn5leBUBBQFSNJqictZXtQ2mJBZ3HCNM7Eb9Ve2YDg8fvROKqaOioTMmpkpN700BLLC6fkyE73+gvuvBL1nksrcpR6Asp8LM3yqksdHq4mJE52up2IR5JKScO/NpuAWfaq6+b5GbjJcUriCCOHTYPb8hCgJFEMUIK0/ALrQA7p2LfHs0YhEDNTAuUTv+rG7Llblnw6LzZ2x9dPL8K6j6QCqiBrWvYAvzQKFHAPJSgg4mP2qY9q7AwkGWI9SDiEFCeTVIeVU5Qi/LMuoXRFSmBIQGNlsdlQm00IQzhNKi++z7o="
  notifications:
  pushover:
    on_success: always
    on_failure: always
    api_key:
      secure: "aGCc23inkUSEf/5VEmndQlkF0yz49f30NaUuIQq8Ub0EDQHpKLti2b2YoTyt6qWLKKLOlsp8yfozBIkvr3RLODGoxtnFqaoOKKcstX2aoqkglcdzp2P3IUz8Qwfx7sCwMPIPprIrU93GKn0k2RQl5tvt7LZLfs44YkqMSogZk+ggxYoMYco51SqQNzjcpTbUtLnK/m/B9NsHktAvLQwwhOf5nawI5R5cRsM+YIayvFcsM8VCJX6bvBo89g6hDst5BNYisCjtHlpvcrZbVm5JdWoyT2z8pvWfqsy1p0Weqtt3+SPDFiJAA/0s5xq+6m3K2Z6ewkpiu6WElogLgbhfIS9dqDvlJUkI5qGKbPL/pfL4m+1BJ8UpfGpgw6Lajaq+Vt6XsXeQBqdUyCYHN/zTc2x596SaqLMIRjrQ2wbosDjt/iecHVg/m7goK6p5XsUMXmwgRL6pp67/huvJU8gVsE/FnQ/7l/EIr5rfGkR8iknuwONG+CJIZ4Idx8GfnK2qhqWE7N2QrPeUyv66jIMtRU97mkhGlQ4eE4NeIHzQ8z4wKS1k80ucaQWEIU0ejY4BEmfPFvcxu7VUTDrhRBcIPNhkUPO81gkcrNWz7ukOoDHNQ+uyb0dOWYU8a+2/8y68mhqMxu2LH5xd62sU38u4hdYYuibF6oxRUBAlkzqY0Y4="
    users:
      secure: "n8BdLWvA99T3+cKcx5S62tSTp4BpJ74FnIGFEAe4yM18puRUotAK7skvN/nS6km7ipwo2Kk+/NuTE4ZEn0UuHAyncOTMA4jUzhAE2JAGMfBjOGxQdHlv777iCKpqohnceD3d2FLo51/2WKjB3m30BGY6vX242SVxJa/W7meJZtm9rVdcR/KF2Zv8ZwQ2Epl7/yxJf8Lti3jP8yru9+K7hNi7+i+K8/ZNIEzrCmOZ2+F9dDUKcijVz95oI77dvizlU68KS70db1hi7iqVU2HcnHGFsx/ogLL7Ft0+LFbGRLRWZHqLqCyw9i6lwm/DxQM+rHFvvgvBuWLpiy53ZMMzvli63OLsNOKfmm/3Ovjij311QOGvgSjN6d3ExF4oiP86MYgy+rOvGDZl+S++kwF+3wLERBSXJXxYkXgcQveXe+OUKgCxOF4DhcA0/LsudCRxHc/h034TTsqGyT7llJmjux7go38ggHbSbLWU3cL4DElCKJIHiT4V3H6gpBi7OPJLo1RB95kBMzHgV1vMs8enaX6NxsS2dO56JPPCrl5thgrjGJ6C1tsLvegH2CbazI+as5vi8/zFdNy3ZIr39cjUH2i0SaO3l4P3BPemiS6UNjmtWZLJAjxV/t4uHRNm2Qyf8oh5zgqTpKxoirE/jfxzzk7ZRx5ZfshVmvx93GVuYYI="
  email:
    on_success: never
    on_failure: change
before_install:
- nvm install 9.5
- gem update --system
- gem install bundler
install:
- npm install -g firebase-tools
- npm install -g gulp-cli
- firebase use its-msp-marketing-site-dev --token "$FIREBASE_TOKEN"
# Unset stripe config before setting environment variables
#- echo "Configuring Stripe test keys"
- echo "Configuring Stripe live keys"
- firebase functions:config:unset stripe --token "$FIREBASE_TOKEN"
- firebase functions:config:set stripe.publishable_key="$STRIPE_PUBLISHABLE_KEY" --token "$FIREBASE_TOKEN"
- firebase functions:config:set stripe.secret_key="$STRIPE_SECRET_KEY" --token "$FIREBASE_TOKEN"
- firebase functions:config:set stripe.webhook_secret="$STRIPE_WEBHOOK_SECRET" --token "$FIREBASE_TOKEN"
- cd functions && npm install && cd ..
- npm install
- bundle install
script:
- cd functions && npm run build
- travis_retry gulp build --prod
after_success:
- firebase --non-interactive deploy --token "$FIREBASE_TOKEN"
#- gulp submit