language: ruby
rvm:
  - 2.2

dist: trusty
sudo: false

branches:
  only:
    - master

cache:
  bundler: true
  yarn: true
  directories:
    - node_modules # NPM packages

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - secure: "K/sEAI2Tgz8TYzU+87xRVm2vOk14nuCTLZc0xRpX52EoHxxN7dVv4QGXQEnBKCj9x2M03rJHmWLxnAgbkv1twR8VMAii0LULXrfa+VMspEfHN+2jEBLOaq941nHWguAjIE1ISt3DYvfxju5MIlPDPMBoe2y4uNFwQNKd6WUUvxBJoh/Klgn2AnucRZA+cvZ46dqEEiDGhl5NOq4ZSH1kh1tXy26F/yWHi1Zj4MiLTDDaQ9UYrCwiFYTFy4wY9JHh98MK+KhSRf4YIQ8dJZNXoFLw93a0wWsWslD5kNxMe9/T+8QvF7FuqEGN2nbpjuv3jf7HxruWUo5VGQXHC+SCcmzeyuKiB07OHPDKaHLFEvOr+0Cz/n8mfRk0urfx/0BLXEXAP/SYVAGs+legmMs6cPGa1hu3UcYU2dSet8oDm4BAzbOmn/CBOImwn+J4MKZ8yQCmaffQuEkIa69UzMoeRrA92Z7ykWu7hkQsTszHKYZqfxOy73PgAqhPrybjdt7/7JzIwcFn0oKnJB6EWNPX/m8cJ2ASlrjSltDcNS/FeRlIwni9ieaGK0NDaCIIgRutYaliwW6cxougFAZTFIjivmc0zSWSqGmo5cDkqOBL3XdD+IM4rRu9OZQ65alv+dSsJjKao9eT6Y/vDCES3rTH89wcMMQ1Fedn2xYj/91OGw8=" # $FIREBASE_TOKEN

notifications:
  email:
    on_success: never
    on_failure: change

install:
  - nvm install 9.5
  - npm install -g gulp-cli

script: travis_retry gulp build --prod

deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "$FIREBASE_API_TOKEN"
  project: "itsolver-499d1"

after_deploy:
  - gulp submit
