language: ruby
rvm:
  - 2.2

dist: trusty
sudo: false

branches:
  only:
    - master

cache:
  bundler: true
  yarn: true
  directories:
    - node_modules # NPM packages

env:
  global:
    - CXX=g++-4.8
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

notifications:
  email:
    on_success: never
    on_failure: change

install:
  - nvm install 6
  - npm install --global gulp-cli
  - npm install --save-dev gulp@next
  - npm install --global yarn
  - yarn

script:
  - gulp build --prod --firebase_api_token=$FIREBASE_API_TOKEN

deploy:
  provider: script
  skip_cleanup: true
  script: gulp deploy
  on:
    branch: master
