language: ruby
rvm:
- 2.4
dist: trusty
sudo: required
branches:
  only:
  - master
cache:
  bundler: true
  yarn: true
  directories:
  - node_modules
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: Yplf+kwWBw8mnhyvWEnjIHiSfgjZv2xU1mmMbTLRc/nPp35n5d36Vx6xm+ogQDeEYO7N1Mq7mKwN2c86ls4703TDfnnEsReSgtzGwQ7hGinFTVQnmf+f589T8kosn5NJNPPjQyWZ7tMZeufM6PRF0hyO2xkibYuFWoj3EoFFEPGXGBVGNNiLjx7XtKsHn4Ec+LbtKTx9hw2O1qZeA5TpfMzkZo4mxR0gViUhcS1QsvlSS5OvknHn9vWTX0rTRku2KgvgH5YVho0WOMPdkD62fj0g0ck6VXqPVrcItFcOkE7Pl9hhiU/v8VyW/4hXfIZAgKVWFhnzOtwxpel580iQLs2+OOTLdpw6c3oWaE81qX0350kq8tqW4qWYMh+s9UqJlkHSKRrUZ6Jv+yJ3FGK8t9XyCEBLKKCc0B+nkTQ/6WpABILC8Pn83O4WtCEZ/n8WBmfUGIeAcWUI3wELMwvumxSwqC64hNeByAdB+O4IwcO/V3O4Lv9snjVF5lEq8bGT5D9YS39yD3sW5k5Euid8gf2O160C+XmkoQT8os4VWWaIm1KZU8kxTr3JYgGPys4TESfCe1lbxFtkifeg+T+Ed8V/5JQj8oyR7xkIvSoMGbkeSKXriepy8jlOWTxXyuk9AAACn7XLp5XV0NFfJSmQKUjp2FZmam5Ufi//TArJI4s=
  - secure: s01OHQ38v/KAKkgMlam2qYX80ND7mHmuN+V1QslQrKaK7sxtzuHYEEj+XPO++xywQIL2ZwzQc6rjvxgcznfSBKj/pnUqjj2KwsL+iPreW9tLX5qtWlQWYtCg1AGW30Vib5dMp2DF68hwYKKmVQqX+bn0jX7Z25FGvgMdXtystwLqmuUyFMiMj+2VxYrawo9E8ic/tp7Z+RmBz3BVodqF7u0D53/RAmP7c4GnIuE7tKSXK1FcqW40DdG77/uzmGKITt17mFCWmYExVw6KFHlPJF9VNkklLeeCnDOmYONlLDK7gPbaz4nP0gjyvK/VHoue9OHI5qgkr46tPNDN2wVeF00L//tGSRtQz/l9oj5C4KzSurUm22X+iC0Iqo1Wj6BV8TwEPoPPp0RcH8yuJWvfAB1LabrS8v6TxxYMWQZcOYRFYrDhO0YCCytaMFVG7MzyT+ONts5cmnwlCTxhQCxNgfNE7hK2aUZVPMlEQTPYBBCYyGjZy9oGk5Ywm/rK1Ae9RcnXiAYl8l5z/HGaa79d26Gp4R3PbGYxZO4nnm5j8ycTIyff3muHdpQVUfqGYrUdNLVubPTI/j92qKMRJ9RGF6xATFRrdbR8DCDiQTfDq1SVJpJHPDjDslDUKzyoqq7YqhRdC2gAlENRkMpgfkIuGntu9Ipmn/rqtiYkEY39iAw=
notifications:
  email:
    on_success: never
    on_failure: change
install:
- nvm install 9.5
- npm install -g gulp-cli
- npm install -g firebase-tools
- npm install
- cd functions && npm install && cd ..
- bundle install
- firebase functions:config:set stripe.token=STRIPETOKEN --token "$FIREBASE_API_TOKEN"
script: travis_retry gulp build --prod
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "$FIREBASE_API_TOKEN"
  project: itsolver-499d1
after_deploy:
- gulp submit
