# ----
# Site
source                   : .tmp/src
destination              : .tmp/dist

title: IT Solver
url: "https://www.itsolver.net"
baseurl:
environment: "production"
repository: https://github.com/itsolver/msp-marketing-site
timezone: Australia/Brisbane
google_analytics_key: "UA-90161029-1"
disqus_shortname:
icon_ready: true
twitter:
  username: itsolvernet
future: false # Publish on schedule future dated posts https://stackoverflow.com/a/5013966

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /the_favicon/android-chrome-192x192.png
description: Computer support and services for small businesses near Redland Bay. IT Solver helps small businesses get the best value from their technology investment.
facebook:
  publisher: https://www.facebook.com/itsolver.net
  admins: gusdoo
author:
  picture: /assets/images/staff-angus.jpg
  twitter: gusmacca
social:
  name: IT Solver
  links:
    - https://www.itsolver.net/blog/
    - https://www.facebook.com/itsolver.net
    - https://www.twitter.com/itsolvernet
    - https://plus.google.com/105525146496759832582
    - https://www.yelp.com.au/biz/it-solver-redland-bay
    - https://foursquare.com/v/it-solver/5a65800a0a08ab7fafc50d49
    - https://github.com/itsolver/msp-marketing-site

defaults:
  - scope:
      path: ""
    values:
      image: /the_favicon/android-chrome-192x192.png

# -----
# Build

collections:
  staff_members:
    _hide_content: false

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: angus
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
  -
    scope:
      path: "contact.html"
    values:
      full_width: false

jekyll-archives:
  enabled:
    - categories
    - tags

plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - build-proof.sh
  - serve-quick.sh
  - serve.sh
  - package.json
  - firebase.json
  - database.rules.json
  - node_modules
  - _script

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google-Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS

_comments:
  map: Update the map location and display settings.
  latitude: Coordinates for the center marker on the map.
  longitude: Coordinates for the center marker on the map.
  zoom: The zoom level for the map.
  pricing_table: Update the information in the pricing tables.
  highlight: Emphasis the text
  color: The background colour used in the plan name and call to action.
  new_window: Open link in new window
