# ----
# Site
environment: development
host                     : 0.0.0.0
profile                  : false
future                   : true
show_drafts              : true

google_site_verification : ""
bing_site_verification   : ""
alexa_site_verification  : ""
yandex_site_verification : ""

google_analytics_key         : ""
